routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\ListingController;
use App\Http\Controllers\Admin\CategoriesCrudController;
use App\Http\Controllers\Admin\ProductCrudController;
use App\Http\Controllers\Admin\SearchController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return Inertia::render('Dashboard');
})->name('dashboard');

Route::GET('/admin/login', [LoginController::class, 'login'])->name('admin.login');

Route::POST('admin/login', [LoginController::class, 'loginPost'])->name('admin.loginPost');

Route::GET('/admin/logout', [LoginController::class, 'logout'])->name('admin.logout');


Route::prefix('admin')->middleware(['admin'])->group(function () {

    Route::GET('/', [LoginController::class, 'dashboard'])->name('admin.dashboard');

    Route::GET('/listing/{model}', [ListingController::class, 'index'])->name('listing.index');

    Route::GET('/search', [SearchController::class, 'search'])->name('search');

    Route::GET('/category/detail/{id}/{name}', [CategoriesCrudController::class, 'categoryClass'])->name('category.categoryClass');

    Route::GET('/category/delete/{id}/{name}', [CategoriesCrudController::class, 'categoryDelete'])->name('category.categoryDelete');

    Route::GET('/product/delete/{id}/{name}', [ProductCrudController::class, 'productDelete'])->name('product.productDelete');


    Route::resource('product', ProductCrudController::class)->except('show', 'destroy');

    Route::resource('category', CategoriesCrudController::class)->except('show', 'destroy');
});

resources/views/admin/add-product.blade.php
@extends('layouts.admin')

@section('contentOne')
    <script>
        var msg = '{{Session::get('messageAdd')}}';
        var exist = '{{Session::has('messageAdd')}}';
        if(exist){
            alert(msg);
        }
    </script>
    <div class="">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="x_panel">
                    <div class="x_title">
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix">
                            <span class="section">Product info</span>
                        </div>
                    </div>
                    <div class="x_content">
                        @if($errors->any())
                            @foreach($errors->all() as $error)
                                <div class="alert alert-danger" role="alert">
                                    {{$error}}
                                </div>
                            @endforeach
                        @endif
                        <form action="{{route('product.store')}}" method="post"  novalidate>
                            @csrf
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Tên sản phẩm<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" type="text" name="name" placeholder="ex. Sữa tươi không đường TH true MILK" required="required" />
                                </div>
                            </div>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Giá sản phẩm<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" type="number" pattern="([0-9]{1,3}).([0-9]{1,3})" name="price" required="required" />
                                </div>
                            </div>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Số lượng<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" type="number" name="quantity" required="required" />
                                </div>
                            </div>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Mô tả sản phẩm<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <textarea class="form-control" type="textarea" name="description" id="description" maxlength="6000" rows="7" placeholder="Description...."></textarea>
                                </div>
                            </div>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Danh mục<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <select  class="form-control categories" name="categories[]" multiple="multiple">
                                        @if($cates)5
                                            @foreach($cates as $cate)
                                        <option value="{{$cate->id}}" >{{$cate->name}}</option>
                                            @endforeach
                                        @endif
                                    </select>
{{--                                   @if($cates)--}}
{{--                                       @foreach($cates as $cate)--}}
{{--                                            <input type="checkbox" name="show_option[]" data-id="{{$cate->id}}" value="{{$cate->id}}">--}}
{{--                                            <label for="{{$cate->name}}"> {{$cate->name}}</label><br>--}}
{{--                                        @endforeach--}}
{{--                                    @endif--}}
                                </div>
                            </div>
                            <div class="ln_solid">
                                <div class="form-group">
                                    <div class="col-md-6 offset-md-3">
                                        <button type='submit' class="btn btn-primary">Submit</button>
                                        <button type='reset' class="btn btn-success">Reset</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/addcategory.blade.php
@extends('layouts.admin')

@section('contentOne')
    <script>
        var msg = '{{Session::get('messageAdd')}}';
        var exist = '{{Session::has('messageAdd')}}';
        if (exist) {
            alert(msg);
        }
    </script>
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Add new category</h3>
            </div>
            <div class="title_right">
                <div class="col-md-5 col-sm-5 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="x_panel">
                    <div class="x_title">
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix">
                            <span class="section">Category info</span>
                        </div>
                    </div>
                    <div class="x_content">
                        @if($errors->any())
                            @foreach($errors->all() as $error)
                                <div class="alert alert-danger" role="alert">
                                    {{$error}}
                                </div>
                            @endforeach
                        @endif
                        <form action="{{route('category.index')}}" method="post" novalidate>
                            @csrf
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Tên danh mục<span
                                        class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" name="name" placeholder="ex. Thực phẩm hữu cơ"
                                           required="required"/>
                                    <br>
                                    <br>
                                </div>

                            </div>
                            <div class="ln_solid">
                                <div class="form-group">
                                    <div class="col-md-6 offset-md-3">
                                        <button type='submit' class="btn btn-primary">Submit</button>
                                        <button type='reset' class="btn btn-success">Reset</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category.blade.php
@extends('layouts.admin')

@section('contentOne')
    <script>
        var msg = '{{Session::get('message')}}';
        var exist = '{{Session::has('message')}}';
        if(exist){
            alert(msg);
        }
    </script>
    <div class="">

        <div class="clearfix"></div>

        <div class="row" style="display: block;">
            <div class="clearfix"></div>
            <div class="col-md-12 col-sm-12  ">
                <div class="x_panel">
                    <div class="x_title">
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>

                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Tên Danh Mục</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($cates)
                                @foreach($cates as $cate)
                                    <tr>
                                        <th scope="row">{{$cate->name}}</th>
                                        <td>
                                            <a href="{{ route('category.edit', $cate->id) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                            <a href="/admin/product/delete/{{$cate->id}}/{{\Str::slug($cate->name)}}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
@endsection

resources/views/admin/categoryClass.blade.php
@extends('layouts.admin')

@section('contentOne')
    <div class="">
        <div class="clearfix"></div>

        <div class="row" style="display: block;">
            <div class="clearfix"></div>
            <div class="col-md-12 col-sm-12  ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Bordered table <small>Bordered table subtitle</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>

                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Tên sản phẩm</th>
                                <th>Giá sản phẩm</th>
                                <th>Số lượng</th>
                                <th>Đã bán</th>
                                <th>Thông tin</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($products)
                                @foreach($products as $product)
                                <tr>
                                    <th scope="row">{{$product->name}}</th>
                                    <td>{{$product->price}}</td>
                                    <td>{{$product->quantity}}</td>
                                    <td>{{$product->selled}}</td>
                                    <td>{{$product->description}}</td>
                                    <td style="width: 200px">
                                        <a href="{{route('product.edit', $product->id)}}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                        <a href="{{route('product.productDelete', [$product->id, $product->name])}}" onclick="return confirm('Bạn chắc chắn xóa sản phẩm này?')" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                                    </td>
                                </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
@endsection

resources/views/admin/edit-category.blade.php
@extends('layouts.admin')

@section('contentOne')
    <script>
        var msg = '{{Session::get('messageAdd')}}';
        var exist = '{{Session::has('messageAdd')}}';
        if(exist){
            alert(msg);
        }
    </script>
    <div class="">
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="x_panel">
                    <div class="x_title">
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        @if($errors->any())
                            @foreach($errors->all() as $error)
                                <div class="alert alert-danger" role="alert">
                                    {{$error}}
                                </div>
                            @endforeach
                        @endif
                        <form action="{{route('category.update', $category->id)}}" method="POST"  novalidate>
                            @method('PATCH')
                            @csrf
                            <span class="section">Edit Category</span>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Tên sản phẩm<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" type="text" name="name" placeholder="ex. Thực phẩm hữu cơ" required="required" value="{{$category->name}}"/>
                                </div>
                            </div>
                                </div>
                            </div>
                            <div class="ln_solid">
                                <div class="form-group">
                                    <div class="col-md-6 offset-md-3">
                                        <button type='submit' class="btn btn-primary">Submit</button>
                                        <button type='reset' class="btn btn-success">Reset</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/edit-product.blade.php
@extends('layouts.admin')

@section('contentOne')
    <script>
        var msg = '{{Session::get('messageAdd')}}';
        var exist = '{{Session::has('messageAdd')}}';
        if(exist){
            alert(msg);
        }
    </script>
    <div class="">
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="x_panel">
                    <div class="x_title">
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        @if($errors->any())
                            @foreach($errors->all() as $error)
                                <div class="alert alert-danger" role="alert">
                                    {{$error}}
                                </div>
                            @endforeach
                        @endif
                        <form action="{{route('product.update', $product->id)}}" method="POST"  novalidate>
                            @method('PATCH')
                            @csrf
                            <span class="section">Product info</span>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Tên sản phẩm<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" type="text" name="name" placeholder="ex. Sữa tươi không đường TH true MILK" required="required" value="{{$product->name}}"/>
                                </div>
                            </div>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Giá sản phẩm<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" type="number" pattern="([0-9]{1,3}).([0-9]{1,3})" name="price" required="required" value="{{$product->price}}"/>
                                </div>
                            </div>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Số lượng<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" type="number" name="quantity" required="required" value="{{$product->quantity}}" />
                                </div>
                            </div>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Mô tả sản phẩm<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <textarea class="form-control" type="textarea" name="description" id="description" maxlength="6000" rows="7" placeholder="Description....">{{$product->description}}</textarea>
                                </div>
                            </div>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Danh mục<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <select  class="form-control categories" name="categories[]" multiple="multiple">
                                        <?php
                                        foreach($cates as $cate){
                                            $flag = 0;
                                            foreach($product->categoriesActive as $item){
                                                if($cate->id == $item->id){
                                                     $flag = 1;
                                                }
                                            }
                                        if ($flag == 0){
                                            echo "<option value=$cate->id> $cate->name </option>";
                                            }
                                            if ($flag == 1){
                                                echo "<option value=$cate->id selected> $cate->name </option>";
                                                $flag = 0;
                                            }
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="ln_solid">
                                <div class="form-group">
                                    <div class="col-md-6 offset-md-3">
                                        <button type='submit' class="btn btn-primary">Submit</button>
                                        <button type='reset' class="btn btn-success">Reset</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/left-menu.blade.php
<div class="navbar nav_title" style="border: 0;">
    <a href="/admin" class="site_title"><i class="fa fa-paw"></i> <span>Foodstore!</span></a>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<div class="profile clearfix">
    <div class="profile_pic">
        <img src="images/img.jpg" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
        <span>Welcome,</span>
        <h2>{{$user->name}}</h2>
    </div>
</div>
<!-- /menu profile quick info -->

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
            <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="{{route('product.index')}}">Sản phẩm</a></li>
                    <li><a href="{{route('category.index')}}">Danh mục</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-edit"></i> Thêm mới <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="{{route('category.create')}}">Danh mục</a></li>
                    <li><a href="{{route('product.create')}}">Sản phẩm</a></li>
                    <li><a href="/admin/admin/create">Thành viên</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-table"></i> Chi tiết danh mục <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    @if($cates)
                        @foreach($cates as $cate)
                            <li><a href="/admin/category/detail/{{$cate->id}}/{{\Str::slug($cate->name)}}">{{$cate->name}}</a></li>
                        @endforeach
                    @endif
                </ul>
            </li>
        </ul>
    </div>
</div>
<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{route('admin.logout')}}">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>
<!-- /menu footer buttons -->

resources/views/admin/product.blade.php
@extends('layouts.admin')

@section('contentOne')
    <script>
        var msg = '{{Session::get('message')}}';
        var exist = '{{Session::has('message')}}';
        if(exist){
            alert(msg);
        }
    </script>
    <div class="">

        <div class="clearfix"></div>

        <div class="row" style="display: block;">
            <div class="clearfix"></div>
            <div class="col-md-12 col-sm-12  ">
                <div class="x_panel">
                    <div class="x_title">
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>

                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Tên sản phẩm</th>
                                <th>Giá sản phẩm</th>
                                <th>Số lượng</th>
                                <th>Đã bán</th>
                                <th>Thông tin</th>
                                <th>Danh mục</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($products)
                                @foreach($products as $product)
                                    <tr>
                                        <th scope="row">{{$product->name}}</th>
                                        <td>{{$product->price}}</td>
                                        <td>{{$product->quantity}}</td>
                                        <td>{{$product->selled}}</td>
                                        <td>{{$product->description}}</td>
                                        <td>
                                            @foreach($product->categoriesActive as $item)
                                                {{$item->name}},
                                            @endforeach
                                        </td>
                                        <td style="width: 200px">
                                            <a href="{{route('product.edit', $product->id)}}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                            <a href="{{route('product.productDelete', [$product->id, $product->name])}}" onclick="return confirm('Bạn chắc chắn xóa sản phẩm này?')" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
@endsection